Changes to the climatology fitting function
oceanobservatories/ooi-data-explorations pull request #58
Opened 2020-12-16 15:02 UTC by reedan88

I updated the fitting of the climatology fitting function to better fit global profilers and risers with small seasonal changes. The current approach overfits the data; the new approach rounds up/down to better constrain the deep data with small changes.

2020-12-16 16:38 UTC, crisien approved these changes

2020-12-16 18:22 UTC, cwingard requested changes
I like the annotations function!! One change needed to the docstring format for that function to match the rest of the code. Also, there several unnecessary carriage returns added to several lines. All of those lines fit within a 120 character limit which is what most code is set to these days (doc strings should be set to 80 characters). The unnecessary carriage returns impact readability and should be avoided whenever possible.

2020-12-16 18:22 UTC, cwingard commented on python/ooi_data_explorations/common.py
> +    """Add the annotation qc flags to a dataset as a data variable.
Please change the docstring formatting to match all the other functions. The code uses the PEP 287 reStructured Text docstring format (https://www.python.org/dev/peps/pep-0287/).

2020-12-21 18:25 UTC, cwingard approved these changes

2020-12-21 18:42 UTC, merged